[package]
name = "util"
description = "Utility functions for the YuvaKriti Language"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]